version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "pxseu"
    commit-message:
      prefix: "⏫"
      prefix-development: "⏫"
    labels:
      - "dependencies"
    open-pull-requests-limit: 5
